### ISSUE TITLE
Vorschlag: Anleitung ergänzen/aktualisieren

### ISSUE THREAD

**Issue by fb4thxUall** [jzakotnik/openlibry#130]
Man könnte den Anleitungstext zur Erstinstallation ergänzen mit ein paar Infos. Mein persönlicher Reminder sieht so aus (funktioniert unter Linux Mint 21.3):

```
#Docker Installation

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update 
sudo apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo usermod -aG docker ${USER}
docker run hello-world
sudo systemctl is-active docker


#Installation von openLibry mit Docker (im Homeverzeichnis):

git clone https://github.com/jzakotnik/openlibry.git
# Anschließend .env-Datei konfigurieren und hinterlegen, docker-compose-yml ändern (restart: always)
cd openlibry
docker build --no-cache -t openlibry .
docker compose up


#Aufrufen im Browser mit lohalhost:3000
#Import des Bestands über Report
```

Für die Produktivumgebung muss der Autostart und Restart des Docker-Containers eingerichtet werden, was am einfachsten geht durch Ergänzung der Docker-Compose Datei "docker-compose.yml", die dann so aussieht:

```
version: "2.0"
services:
  openlibry:
    container_name: openlibry
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./database:/app/prisma/database
      - ./public/coverimages:/app/public/coverimages
    restart: always
```
